services:
  hashcards:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config.toml:/hashcards/config.toml:ro
      - ./cards:/hashcards/cards
      - ./pb_data:/hashcards/data
    environment:
      - TZ=Asia/Tokyo
