services:
  hatchards:
    image: ghcr.io/asano69/hatchards:latest
    container_name: hatchards
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - hatchards.env
    volumes:
      - ./data:/hatchards/pb_data
      - ./cards:/hatchards/cards
      - ./hooks:/hatchards/hooks # optional
      #- /etc/ssl/certs/root_ca.crt:/certs/root_ca.crt:ro # optional
    environment:
      - TZ=Europe/London
      - HATCHARDS_MASTER_KEY=${HATCHARDS_MASTER_KEY} # openssl rand -base64 32
      #
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - DATA_ROOT=./cards
      - FSRS_TARGET_RECALL=0.9
      - FSRS_MIN_INTERVAL=1.0
      - FSRS_MAX_INTERVAL=256.0

      # Not implemented yet
      #- DRILL_CARD_LIMIT=0 # max cards per session, 0 = no limit
      #- DRILL_NEW_CARD_LIMIT=0 # max new cards per session, 0 = no limit
      #- DRILL_ANSWER_CONTROLS=full # "full" (Forgot/Hard/Good/Easy) or "binary" (Forgot/Good)
      #- DRILL_BURY_SIBLINGS=true # bury sibling cloze cards within a session

    #networks:
    #  - traefik_net
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.hatchards.rule=Host(`hatchards.app.internal`)
#volumes:
#  data:
#  cards:
#networks:
#  traefik_net:
#    external: true
